apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.hobby.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: capture
  name: capture
spec:
  containers:
    - env:
        - name: ADDRESS
          value: 0.0.0.0:3000
        - name: CAPTURE_MODE
          value: events
        - name: KAFKA_HOSTS
          value: kafka:9092
        - name: KAFKA_TOPIC
          value: events_plugin_ingestion
        - name: REDIS_URL
          value: redis://redis:6379/
        - name: RUST_LOG
          value: info,rdkafka=warn
      image: ghcr.io/posthog/posthog/capture:master
      name: capture
  restartPolicy: OnFailure
