apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.hobby.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: clickhouse
  name: clickhouse
spec:
  containers:
    - image: clickhouse/clickhouse-server:24.8.7.41
      name: clickhouse
      volumeMounts:
        - mountPath: /idl
          name: clickhouse-claim0
        - mountPath: /docker-entrypoint-initdb.d
          name: clickhouse-claim1
        - mountPath: /etc/clickhouse-server/config.xml
          name: clickhouse-claim2
        - mountPath: /etc/clickhouse-server/config.d/default.xml
          name: clickhouse-claim3
        - mountPath: /etc/clickhouse-server/users.xml
          name: clickhouse-claim4
        - mountPath: /etc/clickhouse-server/user_defined_function.xml
          name: clickhouse-claim5
        - mountPath: /var/lib/clickhouse/user_scripts
          name: clickhouse-claim6
        - mountPath: /var/lib/clickhouse
          name: clickhouse-data
  restartPolicy: OnFailure
  volumes:
    - name: clickhouse-claim0
      persistentVolumeClaim:
        claimName: clickhouse-claim0
    - name: clickhouse-claim1
      persistentVolumeClaim:
        claimName: clickhouse-claim1
    - name: clickhouse-claim2
      persistentVolumeClaim:
        claimName: clickhouse-claim2
    - name: clickhouse-claim3
      persistentVolumeClaim:
        claimName: clickhouse-claim3
    - name: clickhouse-claim4
      persistentVolumeClaim:
        claimName: clickhouse-claim4
    - name: clickhouse-claim5
      persistentVolumeClaim:
        claimName: clickhouse-claim5
    - name: clickhouse-claim6
      persistentVolumeClaim:
        claimName: clickhouse-claim6
    - name: clickhouse-data
      persistentVolumeClaim:
        claimName: clickhouse-data
