apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: clickhouse-claim4
  name: clickhouse-claim4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
