apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.hobby.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: cyclotron-fetch
  name: cyclotron-fetch
spec:
  containers:
    - env:
        - name: DATABASE_URL
          value: postgres://posthog:posthog@db:5432/posthog
        - name: DEBUG
          value: "1"
        - name: JOB_POLL_INTERVAL
          value: 1s
        - name: KAFKA_HOSTS
          value: kafka:9092
        - name: KAFKA_TOPIC
          value: clickhouse_app_metrics2
        - name: MAX_CONCURRENT_JOBS
          value: "10"
        - name: RUST_LOG
          value: info
        - name: SENTRY_DSN
        - name: WORKER_ID
          value: default_worker_id
      image: ghcr.io/posthog/posthog/cyclotron-fetch:master
      name: cyclotron-fetch
  restartPolicy: OnFailure
