apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.hobby.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: cyclotron-janitor
  name: cyclotron-janitor
spec:
  containers:
    - env:
        - name: DATABASE_URL
          value: postgres://posthog:posthog@db:5432/posthog
        - name: KAFKA_HOSTS
          value: kafka:9092
        - name: KAFKA_TOPIC
          value: clickhouse_app_metrics2
        - name: SENTRY_DSN
      image: ghcr.io/posthog/posthog/cyclotron-janitor:master
      name: cyclotron-janitor
  restartPolicy: OnFailure
