apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.hobby.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: db
  name: db
spec:
  containers:
    - env:
        - name: POSTGRES_DB
          value: posthog
        - name: POSTGRES_PASSWORD
          value: posthog
        - name: POSTGRES_USER
          value: posthog
      image: postgres:12-alpine
      livenessProbe:
        exec:
          command:
            - pg_isready -U posthog
        periodSeconds: 5
        timeoutSeconds: 5
      name: db
      volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: db-cm0
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
  restartPolicy: OnFailure
  volumes:
    - configMap:
        name: db-cm0
      name: db-cm0
    - name: postgres-data
      persistentVolumeClaim:
        claimName: postgres-data
