apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.16.2
          ports:
            - containerPort: 9200
              protocol: TCP
          env:
            - name: ES_JAVA_OPTS
              value: -Xms256m -Xmx256m
            - name: cluster.routing.allocation.disk.threshold_enabled
              value: "true"
            - name: cluster.routing.allocation.disk.watermark.flood_stage
              value: 128mb
            - name: cluster.routing.allocation.disk.watermark.high
              value: 256mb
            - name: cluster.routing.allocation.disk.watermark.low
              value: 512mb
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
          volumeMounts:
            - mountPath: /var/lib/elasticsearch/data
              name: elasticsearch-data
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
  labels:
    app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP