apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.hobby.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: livestream
  name: livestream
spec:
  containers:
    - env:
        - name: LIVESTREAM_JWT_SECRET
      image: ghcr.io/posthog/livestream:main
      name: livestream
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /configs/configs.yml
          name: livestream-claim0
  restartPolicy: OnFailure
  volumes:
    - name: livestream-claim0
      persistentVolumeClaim:
        claimName: livestream-claim0
