apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.hobby.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: plugins
  name: plugins
spec:
  containers:
    - args:
        - ./bin/plugin-server
        - --no-restart-loop
      env:
        - name: CDP_REDIS_HOST
          value: redis7
        - name: CDP_REDIS_PORT
          value: "6379"
        - name: CLICKHOUSE_DATABASE
          value: posthog
        - name: CLICKHOUSE_HOST
          value: clickhouse
        - name: CLICKHOUSE_SECURE
          value: "false"
        - name: CLICKHOUSE_VERIFY
          value: "false"
        - name: CYCLOTRON_DATABASE_URL
          value: postgres://posthog:posthog@db:5432/posthog
        - name: DATABASE_URL
          value: postgres://posthog:posthog@db:5432/posthog
        - name: ENCRYPTION_SALT_KEYS
        - name: KAFKA_HOSTS
          value: kafka:9092
        - name: OBJECT_STORAGE_ACCESS_KEY_ID
          value: object_storage_root_user
        - name: OBJECT_STORAGE_ENABLED
          value: "true"
        - name: OBJECT_STORAGE_ENDPOINT
          value: http://objectstorage:19000
        - name: OBJECT_STORAGE_SECRET_ACCESS_KEY
          value: object_storage_root_password
        - name: PERSONS_DATABASE_URL
          value: postgres://posthog:posthog@db:5432/posthog
        - name: REDIS_URL
          value: redis://redis:6379/
        - name: SECRET_KEY
        - name: SENTRY_DSN
        - name: SESSION_RECORDING_V2_S3_ENDPOINT
          value: http://objectstorage:19000
        - name: SITE_URL
          value: https://
      image: 'posthog/posthog:latest'
      name: plugins
  restartPolicy: OnFailure
