apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.hobby.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: property-defs-rs
  name: property-defs-rs
spec:
  containers:
    - env:
        - name: DATABASE_URL
          value: postgres://posthog:posthog@db:5432/posthog
        - name: FILTER_MODE
          value: opt-out
        - name: KAFKA_HOSTS
          value: kafka:9092
        - name: SKIP_READS
          value: "false"
        - name: SKIP_WRITES
          value: "false"
      image: ghcr.io/posthog/posthog/property-defs-rs:master
      name: property-defs-rs
  restartPolicy: OnFailure
