apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.hobby.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: replay-capture
  name: replay-capture
spec:
  containers:
    - env:
        - name: ADDRESS
          value: 0.0.0.0:3000
        - name: CAPTURE_MODE
          value: recordings
        - name: KAFKA_HOSTS
          value: kafka:9092
        - name: KAFKA_TOPIC
          value: session_recording_snapshot_item_events
        - name: REDIS_URL
          value: redis://redis:6379/
      image: ghcr.io/posthog/posthog/capture:master
      name: replay-capture
  restartPolicy: OnFailure
