apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.hobby.yml convert
    kompose.version: 1.34.0 (cbf2835db)
    kompose.volume.type: configMap
  labels:
    io.kompose.service: temporal
  name: temporal
spec:
  containers:
    - env:
        - name: DB
          value: postgresql
        - name: DB_PORT
          value: "5432"
        - name: DYNAMIC_CONFIG_FILE_PATH
          value: config/dynamicconfig/development-sql.yaml
        - name: ENABLE_ES
          value: "false"
        - name: ES_SEEDS
          value: elasticsearch
        - name: ES_VERSION
          value: v7
        - name: POSTGRES_PWD
          value: posthog
        - name: POSTGRES_SEEDS
          value: db
        - name: POSTGRES_USER
          value: posthog
      image: temporalio/auto-setup:1.20.0
      name: temporal
      ports:
        - containerPort: 7233
          protocol: TCP
      volumeMounts:
        - mountPath: /etc/temporal/config/dynamicconfig
          name: temporal-claim0
  restartPolicy: OnFailure
  volumes:
    - name: temporal-claim0
      persistentVolumeClaim:
        claimName: temporal-claim0
