apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: ./kompose -f docker-compose.hobby.yml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  containers:
    - image: zookeeper:3.7.0
      name: zookeeper
      volumeMounts:
        - mountPath: /datalog
          name: zookeeper-datalog
        - mountPath: /data
          name: zookeeper-data
        - mountPath: /logs
          name: zookeeper-logs
  restartPolicy: OnFailure
  volumes:
    - name: zookeeper-datalog
      persistentVolumeClaim:
        claimName: zookeeper-datalog
    - name: zookeeper-data
      persistentVolumeClaim:
        claimName: zookeeper-data
    - name: zookeeper-logs
      persistentVolumeClaim:
        claimName: zookeeper-logs
